# Azul-zulu java11 Alpine image
FROM azul/zulu-openjdk-alpine:11

# project build
LABEL maintainer="mina1316.canreply@gmail.com"

VOLUME /tmp

EXPOSE 8080 5005

ADD ./build/libs/webapp-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-Djava.security.egd", "-Xdebug", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005", "-jar", "/app.jar"]