
version: 2.1

jobs:
  build:
    docker:
      - image: azul/zulu-openjdk-alpine:18.0.2-18.32.11-jre
    steps:
#     start gradle wrapper to build the project
      - checkout
      - run: cd ./backend && ./gradlew build

  lint:
    docker:
      - image: azul/zulu-openjdk-alpine:18.0.2-18.32.11-jre
    steps:
#     start gradle wrapper to check lint statue of the project
      - checkout
      - run: .cd ./backend && ./gradlew checkstyleMain checkstyleTest

  test:
    docker:
      - image: azul/zulu-openjdk-alpine:18.0.2-18.32.11-jre
    steps:
#     start gradle wrapper to test the project
      - checkout
      - run: cd ./backend && ./gradlew test

workflows:
  pull_request:
    jobs:
      - build:
          filters:
            branches:
              only: develop-backend
      - lint:
          filters:
            branches:
              only: develop-backend
      - test:
          filters:
            branches:
              only: develop-backend