
version: 2.1

jobs:
  build:
    docker:
      - image: mina1316/azul-zulu-openjdk-alpine-git:11-jre 
    steps:
#     start gradle wrapper to build the project
      - run: git clone -b develop-backend https://github.com/Dobby-Needs-Portfolio/2022-StudyMatching.git .
      - run: ls
      - run: cd ./backend && ./gradlew assemble

  lint:
    docker:
      - image: mina1316/azul-zulu-openjdk-alpine-git:11-jre
    steps:
#     start gradle wrapper to check lint statue of the project
      - run: git clone -b develop-backend https://github.com/Dobby-Needs-Portfolio/2022-StudyMatching.git .
      - run: cd ./backend && ./gradlew checkstyleMain checkstyleTest

  test:
    docker:
      - image: mina1316/azul-zulu-openjdk-alpine-git:11-jre
    steps:
#     start gradle wrapper to test the project
      - run: git clone -b develop-backend https://github.com/Dobby-Needs-Portfolio/2022-StudyMatching.git .
      - run: cd ./backend && ./gradlew test --scan

workflows:
  pull_request:
    jobs:
      - build:
          filters:
            branches:
              only: develop-backend
      - lint:
          filters:
            branches:
              only: develop-backend
      - test:
          filters:
            branches:
              only: develop-backend